### ISSUE TITLE
🐞 File view crashes when rolling on table via block reference that does not exist

### ISSUE THREAD

**Issue by Restioson** [javalent/dice-roller#363]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The dice roller expression fails to work, but the markdown file still loads.

### Current behaviour

A "failed to open" toast appears in the top left, along with the following logs in console:
```
Uncaught (in promise) Error: Could not read file cache. Does the block reference exist?

Encounter Building Tables > wilderness-points-of-interest
    at r.getOptions (plugin:obsidian-dice-roller:3062:1821)
    at r.onload (plugin:obsidian-dice-roller:3050:1834)

RangeError: Decorations that replace line breaks may not be specified via plugins
    at e.point (app.js:1:339025)
    at e.spans (app.js:1:295577)
    at e.build (app.js:1:340067)
    at t.updateChildren (app.js:1:355362)
    at t.updateInner (app.js:1:353846)
    at t.update (app.js:1:353650)
    at e.update (app.js:1:443479)
    at e.dispatchTransactions (app.js:1:440040)
    at e.dispatch (app.js:1:442028)
    at t.set (app.js:1:1622386)
(anonymous) @ app.js:1
```

(second not necessarily related)

### Reproduction

Make one file called `Encounter Building Tables.md` with no content.

Make another file called `Random.md` and add the following content
```md
`dice+: [[Encounter Building Tables^askjdasjhbd]]
```

Enable the plugin and try to open the Random page again. It should crash

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.7.7 and 1.4.16

### Plugin Version

11.4.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

Handle the error in the promise - haven't looked in the code but this should probably just be caught and propagated upward to fail instead of throwing to console

**Comment by Restioson** [comment]
Think this is mis-reported. I previously had it crashing when the block was unknown, and then fixed it by making it a real block (there was a typo), but now even the real block does not work, so it must be something about that block instead. I will upload the full files to a gist

**Comment by Restioson** [comment]
I've edited the original submission with a confirmed MRE
